receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

  # prometheus:
  #   config:
  #     scrape_configs:
  #       # Collector metrics
  #       - job_name: 'otel-collector'
  #         scrape_interval: 10s
  #         static_configs:
  #         - targets: [ '0.0.0.0:8888' ]

processors:
  batch: {}
  cumulativetodelta:
      max_staleness: 25h

  # Prevent out of memory (OOM) situations on the Collector
  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 30

exporters:
  debug:
    verbosity: basic

extensions:
  opamp:
    server:
      ws:
        endpoint: wss://opamp-server:4320/v1/opamp
        tls:
          insecure_skip_verify: true
    capabilities:
      reports_effective_config: true

service:
  extensions: [opamp]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, cumulativetodelta, batch ]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug ]

  telemetry:
    metrics:
      level: detailed
      readers:
      - periodic:
          exporter:
            otlp:
              endpoint: http://0.0.0.0:4318
              protocol: http/protobuf
              temporality_preference: delta
          interval: 10000
          timeout: 5000
    logs:
      level: debug
      output_paths: ["stdout"]
      error_output_paths: ["stderr"]